# -*- coding: utf-8 -*-
"""Double Sersic fitting analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yix0LSrykNVJKl-1T6cgrOousZUql9Cw
"""

!pip install autoconf==2024.11.13.2 autofit==2024.11.13.2 autoarray==2024.11.13.2 autogalaxy==2024.11.13.2 pyvis==0.3.2 dill==0.3.1.1 dynesty==2.1.4 emcee==3.1.6 nautilus-sampler==1.0.4 timeout_decorator==0.5.0 anesthetic==2.8.14 --no-deps
!pip install numba
!git clone https://github.com/Jammy2211/BSc_Galaxies_Project
import os
from autoconf import conf

os.chdir("/content/BSc_Galaxies_Project")

conf.instance.push(
    new_path="/content/BSc_Galaxies_Project/",
    output_path="/content/BSc_Galaxies_Project/output",
)

import numpy as np
import autogalaxy as ag
import autogalaxy.plot as aplt
from os import path

import autofit as af

dataset_name = "" #enter required dataset here
dataset_path = path.join("dataset", "task_6a_bars", dataset_name)

dataset = ag.Imaging.from_fits(
    data_path=path.join(dataset_path, "data.fits"),
    noise_map_path=path.join(dataset_path, "noise_map.fits"),
    psf_path=path.join(dataset_path, "psf.fits"),
    pixel_scales=0.06,
)

dataset_plotter = aplt.ImagingPlotter(dataset=dataset)
dataset_plotter.subplot_dataset()

# Masking
mask = ag.Mask2D.circular(
    shape_native=dataset.shape_native, pixel_scales=dataset.pixel_scales, radius=6.0
)

dataset = dataset.apply_mask(mask=mask)

dataset_plotter = aplt.ImagingPlotter(dataset=dataset)
dataset_plotter.subplot_dataset()

# Galaxy
# Disk component
disk = ag.lp.Sersic(
    centre=(0.0, 0.0),
    ell_comps=(0.0, 0.0),
    intensity=0.01,
    effective_radius=6.0,
    sersic_index=3.0,
)
# Bulge component
bulge = ag.lp.Sersic(
    centre=(0.0, 0.0),
    ell_comps=(0.4, 0.01),
    intensity=3.00,
    effective_radius=2.0,
    sersic_index=0.5,
)

# Galaxy model
galaxy_model = af.Model(ag.Galaxy, redshift=0.5, disk=ag.lp_linear.Sersic, bulge=ag.lp_linear.Sersic)

model = af.Collection(galaxies=af.Collection(galaxy=galaxy_model))

print(model.info)

# Priors
#Priors disk
model.galaxies.galaxy.disk.centre.centre_0 = af.UniformPrior(lower_limit=-0.01, upper_limit=0.01)
model.galaxies.galaxy.disk.centre.centre_1 = af.UniformPrior(lower_limit=-0.01, upper_limit=0.01)
model.galaxies.galaxy.disk.ell_comps.ell_comps_0 = af.UniformPrior(
    lower_limit=-0.1, upper_limit=0.1
)
model.galaxies.galaxy.disk.ell_comps.ell_comps_1 = af.UniformPrior(
    lower_limit=-0.1, upper_limit=0.1
)
model.galaxies.galaxy.disk.effective_radius = af.UniformPrior(
    lower_limit=0.0, upper_limit=6.0
)
model.galaxies.galaxy.disk.sersic_index = af.UniformPrior(
    lower_limit=0.0, upper_limit=2.0
)

# Priors bulge
model.galaxies.galaxy.bulge.centre.centre_0 = af.UniformPrior(lower_limit=-0.1, upper_limit=0.1)
model.galaxies.galaxy.bulge.centre.centre_1 = af.UniformPrior(lower_limit=-0.1, upper_limit=0.1)
model.galaxies.galaxy.bulge.ell_comps.ell_comps_0 = af.UniformPrior(
    lower_limit=-1.0, upper_limit=1.0
)
model.galaxies.galaxy.bulge.ell_comps.ell_comps_1 = af.UniformPrior(
    lower_limit=-1.0, upper_limit=1.0
)
model.galaxies.galaxy.bulge.effective_radius = af.UniformPrior(
    lower_limit=0.0, upper_limit=6.0
)
model.galaxies.galaxy.bulge.sersic_index = af.UniformPrior(
    lower_limit=0.50, upper_limit=0.51
)

print(model.info)

#Analysis
analysis = ag.AnalysisImaging(dataset=dataset)

# Nested sampling algorthm
search = af.Nautilus(
    name="example_0",
    n_live=1000,
    iterations_per_update=3000,
    force_x1_cpu=True # This ensures the Google Colab code runs correctly
)

print(
    """
    The non-linear search has begun running.
    This Jupyter notebook cell with progress once the search has completed
    """
)

result = search.fit(model=model, analysis=analysis)

print("The search has finished run - you may now continue the notebook.")

print(result.info)

fit_plotter = aplt.FitImagingPlotter(fit=result.max_log_likelihood_fit)
fit_plotter.subplot_fit()

from google.colab import files

!zip -r output.zip /content/BSc_Galaxies_Project/output
files.download("output.zip")

from google.colab import files

!zip -r output.zip /content/BSc_Galaxies_Project/output
files.download("output.zip")